export default [
  {
    id: 1,
    author: "Oyekanmi",
    image: "https://i.ibb.co/G9cnmDD/Screenshot-19.png",
    name: "navbar js",
    language: ["html", "css", "javascript"],
    category: "javascript",
    url: "https://oyekanm.github.io/Navigation-js/",
    Github: "https://github.com/oyekanm/Navigation-js",
    viewModal: false,
  },
  {
    id: 2,
    author: "Oyekanmi",
    image: "https://i.ibb.co/1vNy5Sg/Screenshot-8.png",
    name: "clone",
    language: ["html", "css", "bootstrap"],
    category: "html/css",
    url: "https://clonedcss.netlify.app/",
    Github: "https://github.com/oyekanm/Clone",
    viewModal: false,
  },
  {
    id: 3,
    author: "Oyekanmi",
    image: "https://i.ibb.co/0ydvtBW/Screenshot-7.png",
    name: "counting app",
    language: ["html", "css", "javascript"],
    category: "javascript",
    url: "https://oyekanm.github.io/Counting-App/",
    Github: "https://github.com/oyekanm/Counting-App",
    viewModal: false,
  },
  {
    id: 4,
    author: "Oyekanmi",
    image: "https://i.ibb.co/CtPyLWx/Screenshot-5.png",
    name: "order summary",
    language: ["html", "css"],
    category: "html/css",
    url: "https://subscription.netlify.app/",
    Github: "https://github.com/oyekanm/Order-summary",
    viewModal: false,
  },
  {
    id: 5,
    author: "Oyekanmi",
    image: "https://i.ibb.co/5GVD76B/Screenshot-11.png",
    name: "natours",
    language: ["html", "css", "sass"],
    category: "sass",
    url: "https://oyekanm.github.io/NATOURS/",
    Github: "https://github.com/oyekanm/NATOURS",
    viewModal: false,
  },
  {
    id: 6,
    author: "Oyekanmi",
    image: "https://i.ibb.co/30QNFyP/Screenshot-13.png",
    name: "trillo",
    language: ["html", "css", "sass"],
    category: "sass",
    url: "https://oyekanm.github.io/TRILLO/",
    Github: "https://github.com/oyekanm/TRILLO",
    viewModal: false,
  },
  {
    id: 7,
    author: "Oyekanmi",
    image: "https://i.ibb.co/YfQPvjr/Screenshot-12.png",
    name: "nexter",
    language: ["html", "css", "sass"],
    category: "sass",
    url: "https://nextergrid.netlify.app/",
    Github: "https://github.com/oyekanm/NEXTER",
    viewModal: false,
  },
  {
    id: 8,
    author: "Oyekanmi",
    image: "https://i.ibb.co/YN7MtN3/Screenshot-4.png",
    name: "black jack",
    language: ["html", "css", "javascript"],
    category: "javascript",
    url: "https://oyekanm.github.io/Black-Jack/",
    Github: "https://github.com/oyekanm/Black-Jack",
    viewModal: false,
  },
  {
    id: 9,
    author: "Oyekanmi",
    image: "https://i.ibb.co/9Nq7hWs/Screenshot-6.png",
    name: "chrome extension",
    language: ["html", "css", "javascript"],
    category: "javascript",
    url: "https://oyekanm.github.io/Chrome-Ext/",
    Github: "https://github.com/oyekanm/Chrome-Ext",
    viewModal: false,
  },

  {
    id: 10,
    author: "Oyekanmi",
    image: "https://i.ibb.co/VL0tF9H/Screenshot-3.png",
    name: "carousel",
    language: ["html", "css", "javascript"],
    category: "javascript",
    url: "https://oyekanm.github.io/Carousel/",
    Github: "https://github.com/oyekanm/Carousel",
    viewModal: false,
  },
];
